- name: CrackMapExec
  hosts: all
  tasks:
    - name: Install core deps
      apt:
        name:
          - libssl-dev
          - libffi-dev
          - python-dev
          - build-essential

    - name: Clone repo
      git:
        repo: https://github.com/byt3bl33d3r/crackmapexec
        dest: "{{ ansible_env.HOME }}/Tools/crackmapexec"

    - name: Install via pipenv
      shell: |
        pipenv install
        pipenv run python setup.py install
      args:
        chdir: "{{ ansible_env.HOME }}/Tools/crackmapexec"
