- name: SprayingToolkit
  hosts: all
  tasks:
    - name: Install core deps
      apt:
        name:
          - python3

    - name: Clone repo
      git:
        repo: https://github.com/byt3bl33d3r/SprayingToolkit
        dest: "{{ ansible_env.HOME }}/Tools/sprayingtoolkit"

    - name: Install via pipenv
      shell: |
        pipenv install
      args:
        chdir: "{{ ansible_env.HOME }}/Tools/sprayingtoolkit"
